### ISSUE TITLE
Wrong http status code (500) returned instead of 404 or any response thrown from a loader.

### ISSUE THREAD

**Issue by zvin** [remix-run/blues-stack#145] opened 2023-01-17 16:12 UTC
### Have you experienced this bug with the latest version of the template?

yes

### Steps to Reproduce

 * `npx create-remix@latest`;
 * select the blues template, follow the suggested steps;
 * go to any page that doesn't exist, http://0.0.0.0:3000/no-such-page for example
 * see that the returned status is `500` instead of `404`

The same issue happens if you throw a json response in a loader: `throw json("Unauthorized", { status: 403 });`, a 500 status code will be returned to the browser.

It seems like this started happening when updating remix from `1.9.0` to `1.10.0`.
The issue does not happen when using `remix serve` instead of `express`.
I don't know if the issue comes from the template `server.ts` file or from the combination of `@remix-run/react` and `@remix-run/express`

### Expected Behavior

A 404 http status code should be returned.
![Capture d’écran du 2023-01-17 20-02-01](https://user-images.githubusercontent.com/180331/212951409-16a562cf-b46f-498a-8d54-325c48f411a7.png)

### Actual Behavior

A 500 http status code is returned.
![Capture d’écran du 2023-01-17 19-45-26](https://user-images.githubusercontent.com/180331/212951467-abfa463c-be8d-41fb-b4a8-b66e99604e21.png)

**Comment by zvin** [comment] 2023-01-17 18:26
Minimal reproduction here: https://stackblitz.com/edit/node-zxrwpd

**Comment by zvin** [comment] 2023-01-18 12:30
One thing that solves the issue is to remove the eslint `--bundle` flag [here](https://github.com/remix-run/blues-stack/blob/main/package.json#L9)

**Comment by machour** [comment] 2023-01-18 12:34
This is an intended behavior in production, see Matt's answer here: https://github.com/remix-run/remix/issues/5115#issuecomment-1386043115

**Comment by zvin** [comment] 2023-01-18 13:10
The issue does not happen when not using `eslint`'s `--bundle` flag or running `server.ts` with `ts-node` directly.

**Comment by brophdawg11** [comment] 2023-01-18 22:20
The above merged PR will go in the next react router release, either 6.7.1 or 6.8.0 depending on what is in it.  Then Remix will pick that up in it's next release.

**Comment by zvin** [comment] 2023-01-19 12:00
Thanks for the quick fix!

**Comment by brophdawg11** [comment] 2023-01-26 18:31
This should be fixed with Remix `1.12.0` which should be out in the next hour or two

**Closed** 2023-04-13 14:48 UTC
