### ISSUE TITLE
Build Fails on 404

### ISSUE THREAD

**Issue by victorias** [remix-run/blues-stack#32] opened 2022-03-24 22:22 UTC
Hi guys,

Love the project and super excited to get started. I setup everything on a fresh machine and a fresh and got this error in the Docker build step on github actions. I've removed the first part of the log for brevity since it looked fine at a glance, but happy to add more information if necessary. It might be a transient error/network issue, but I've rerun the build a couple of times (~3) and am still getting the issue.
Hoping, y'all can help! Thanks so much!

```#19 [build 7/7] RUN npm run build
#19 3.306 Building Remix app in production mode...
#19 3.771 Built in 464ms
#19 4.060 
#19 4.060 > build:server
#19 4.060 > esbuild --platform=node --format=cjs ./server.ts --outdir=build
#19 4.060 
#19 4.070 
#19 4.070   build/server.js  3.2kb
#19 4.070 
#19 4.070 ⚡ Done in 2ms
#19 DONE 4.1s

#20 [stage-4 3/6] COPY --from=build /myapp/node_modules/.prisma /myapp/node_modules/.prisma
#20 DONE 0.2s

#21 [stage-4 4/6] COPY --from=build /myapp/build /myapp/build
#21 DONE 0.0s

#22 [stage-4 5/6] COPY --from=build /myapp/public /myapp/public
#22 DONE 0.0s

#23 [stage-4 6/6] ADD . .
#23 DONE 0.0s

#24 exporting to image
#24 exporting layers
#24 exporting layers 7.5s done
#24 ...

#25 [auth] sharing credentials for registry.fly.io
#25 DONE 0.0s

#24 exporting to image
#24 exporting manifest sha256:555d69678b1111c7d39670e6497734a0b7233b421ef5a9730d41395eb00572b2 done
#24 exporting config sha256:271e7ab0d8eb33f55a70d4e4584f41b69032788c90ae6[323](https://github.com/victorias/worth/runs/5683958837?check_suite_focus=true#step:8:323)0dae105f5a3c419a done
#24 pushing layers
#24 pushing layers 0.1s done
#24 ERROR: unexpected status: 404 Not Found
------
 > exporting to image:
------
error: failed to solve: unexpected status: 404 Not Found
Error: buildx failed with: error: failed to solve: unexpected status: 404 Not Found````

**Comment by kentcdodds** [comment] 2022-03-25 00:01
Hi @victorias,

Make certain that the token you have was generated in the browser with the same fly account that created the app in the terminal (some have had that problem before). Otherwise you'll need to ask the fly community. There's a link in the README.

If you find something we can do in this project to improve or avoid this, let us know, but I'm going to close this issue since there isn't much we can do.

**Closed by kentcdodds** 2022-03-25 00:01 UTC

**Comment by davidloiret** [comment] 2022-03-25 10:07
Hi @kentcdodds 
Auth seems OK (#25)
I encountered the same problem, the issue is that `app` field in `fly.toml` should be updated according to the current project app name.
